Repository Agrover112/bash_utils, pull requests merged in 2022-10, with the labels that each got.

#5 Update bash_aliases.sh by himpat202
  bash_aliases.sh
Labels: hacktoberfest, hacktoberfest 2022, hactoberfest-accepted

#6 fix: Fix & rename alias
  bash_aliases.sh
Labels: hacktoberfest, hacktoberfest 2022, hacktoberfest-accepted

#7 Update bash_aliases.sh
  bash_aliases.sh
Labels: bug, hacktoberfest-accepted

#8 Issue #1 fix and adding more aliases
  bash_aliases.sh
Labels: hacktoberfest, hacktoberfest 2022, hactoberfest-accepted, hacktoberfest-accepted

#9 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: hacktoberfest 2022, hactoberfest-accepted, hacktoberfest-accepted

#11 Installation script
  install.sh
Labels: hacktoberfest, hacktoberfest 2022, hacktoberfest-accepted
